### ISSUE TITLE
All options toolbar visible when parent block is active

### ISSUE THREAD

**Issue by afbora** [jongacnik/kirby-fields-block#4]
From discord by `smngy`

> However when the parent block is active the options ui for the child blocks are all show together 

![ddUbsV_w](https://user-images.githubusercontent.com/3393422/136085418-6f948df2-e08c-4b9d-84f8-254cdb73acfd.png)

**Comment by medienbaecker** [comment]
FYI: I can no longer reproduce this issue. Not sure which Kirby update solved it.
