### ISSUE TITLE
Could this please be added to Kirby's official plugins list?

### ISSUE THREAD

**Issue by trych** [jongacnik/kirby-fields-block#6]
It's not in Kirby's official plugin list? Could it be added there?

Process is described on the bottom of [this page](https://getkirby.com/docs/guide/plugins/best-practices).

Thanks!

**Comment by medienbaecker** [comment]
This issue can be closed: https://getkirby.com/plugins/jongacnik/fields-block

**Comment by jongacnik** [comment]
Hey thanks for the help 😅 It's often the smallest things I don't get around to.
