### ISSUE TITLE
Double click on a word

### ISSUE THREAD

**Issue by theamnesic** [jongacnik/kirby-fields-block#7]
Hi! 

With a Text field, I can't select a word by clicking twice on it as the normal field.

With the plugin: 

![kirby](https://user-images.githubusercontent.com/242203/152789523-8b177d15-03bb-4496-b652-97ca57b9f249.gif)

Without: 

![output](https://user-images.githubusercontent.com/242203/152789674-fc80158a-cad2-429b-a763-bb6e31c315a6.gif)

Is there a way to enable double click?

Thanks!

**Comment by dennisbaum** [comment]
Same behavior for me. unfortenetly i can't select any text or url by a double-click. 
interestingly I can select everything by clicking on the label of i.e. a text, textarea or url - but only in ff.

**Comment by jongacnik** [comment]
Merged #9
